title: 北高文藝部
brand: Cheni Yuki Yang
baseurl: ""
url: "https://typ.moe"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
