title: Brethland's Blog
brand: Brethland's Blog
description:
baseurl: ""
url: "https://njupt-sast-technology-center.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

excerpt_separator: <!--more-->
